### ISSUE TITLE
Error trying to add DQOps connection to DuckDB using the CLI

### ISSUE THREAD

**Issue by datamike** [dqops/dqo#20] opened 2024-04-26 02:52 UTC
dqo> `connection add --duckdb-directories=<"path"="/folder1/subfolder2/my-salesforce-pipeline">`

Command failed, error message: Cannot invoke "com.dqops.cli.terminal.TerminalFactory.getReader()" because "this.terminalFactory" is null

Not sure what the proper syntax for the console command.

I tried to do a similar thing using the Web interface and got this error: 

> com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Invalid Input Error: Unrecognized configuration property "path"

Thanks.

**Comment by dqops** [comment] 2024-04-26 12:54
Here are three issues or problems:

1) The error with the null value is a bug. It was just fixed in the develop branch.

2) The path that was used should not contain "<" and ">", because these are just the placeholders from the documentation (command line synopsis) generated by PicoCli. They just show where a parameter value provided by a user starts and ends.

3) We can't reproduce the problem with the unrecognized "path" configuration parameter. Was the "path" parameter added to the list of custom parameters for the JDBC driver? If so, it is not the right place because the DuckDB driver does not use that sort of configuration. The connection configuration screen shows a list of paths. The paths that are defined for a new connection are the paths to the folders with flat files.

**Closed** 2024-04-26 12:55 UTC
Labels: bug
